TallleresPaco/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TallleresPaco.Models;
/*using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;*/
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Kernel.Font;
using iText.IO.Font.Constants;

namespace TallleresPaco.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly Contexto _context;

        public UsuariosController(Contexto context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios
                         .Where(u => u.Estado != "Baja")
                         .ToListAsync());

        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre,Apellido,FechaNacimiento,Dni,Estado")] UsuarioRegistroViewModel ur)
        {
            if (ModelState.IsValid)
            {
                Usuarios usuarios = new Usuarios() { 
                    Nombre = ur.Nombre,
                    Apellido = ur.Apellido,
                    FechaNacimiento = ur.FechaNacimiento,
                    Dni = ur.Dni,
                    Estado = ur.Estado,
                };
                _context.Add(usuarios);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ur);
        }

        // GET: Usuarios/Edit/5
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
                return NotFound();

            var currentUserEmail = User.Identity.Name;
            var userIsAdmin = User.IsInRole("Admin");

            if (!userIsAdmin && usuario.Email != currentUserEmail)
            {
                return Forbid(); 
            }

            var vm = new UsuarioRegistroViewModel
            {
                Nombre = usuario.Nombre,
                Apellido = usuario.Apellido,
                FechaNacimiento = usuario.FechaNacimiento,
                Dni = usuario.Dni,
                Estado = usuario.Estado
            };

            return View(vm);
        }
        // GET: Usuarios/Edit/5

        [Authorize]
        public async Task<IActionResult> EditProfile()
        {
            var userEmail = User.Identity.Name;

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(u => u.Email == userEmail); // o Dni, etc

            if (usuario == null)
                return NotFound();

            return RedirectToAction("Edit", new { id = usuario.Id });
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Edit(int id, UsuarioRegistroViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }

            // Actualizar los campos
            usuario.Nombre = vm.Nombre;
            usuario.Apellido = vm.Apellido;
            usuario.FechaNacimiento = vm.FechaNacimiento;
            usuario.Dni = vm.Dni;
            usuario.Estado = vm.Estado;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                usuario.Estado = "Baja";
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool UsuariosExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }
        [Authorize]
        public async Task<IActionResult> Manage()
        {
            return View("Manage/Index");

        }

        // 1. Obtener usuarios registrados últimos 2 meses
        public async Task<IActionResult> UsuariosRecientes()
        {
            var dosMesesAtras = DateTime.Now.AddMonths(-2);

            var usuarios = await _context.Usuarios
                .Where(u => u.FechaNacimiento >= dosMesesAtras && u.Estado == "Activo")
                .Select(u => new UsuarioReporte
                {
                    Id = u.Id,
                    NombreCompleto = u.Nombre + " " + u.Apellido,
                    FechaRegistro = u.FechaNacimiento,
                    Email = u.Email
                })
                .ToListAsync();

            var vm = new ReportesViewModel { UsuariosRecientes = usuarios };
            return View("Manage/UsuariosRecientes", vm);
        }


      

        // 3. Descargar PDF con todos los vehículos (solo paso datos, el PDF se genera en la vista o servicio)
        public async Task<IActionResult> DescargarVehiculosPdf()
        {
            var vehiculos = await _context.Vehiculos
                .Select(v => new VehiculoReporte
                {
                    IdVehiculo = v.Id,
                    Matricula = v.Matricula,
                    Modelo = v.Modelo,
                    Marca = v.Marca,
                    Color = v.Color,
                    AnioFab = v.AnioFab,
                    Precio = v.Precio,
                    Categoria = v.Categoria
                }).ToListAsync();


            byte[] pdfBytes = GenerarPDFVehiculos(vehiculos);

            return File(pdfBytes, "application/pdf", "Listado_Vehiculos.pdf");
            /*// Generar PDF con QuestPDF --> Como peta la funcion tambien peta aqui
            var pdfBytes = GenerateVehiculosPdf(vehiculos);

            return File(pdfBytes, "application/pdf", "Vehiculos.pdf");*/
        }
        private byte[] GenerarPDFVehiculos(List<VehiculoReporte> vehiculos)
        {
            using (var memoryStream = new MemoryStream())
            {
                var writer = new PdfWriter(memoryStream);
                var pdf = new PdfDocument(writer);
                var document = new Document(pdf);

                // Título del documento
                var titulo = new Paragraph("Listado de Vehículos")
                    .SetFontSize(20)
                    .SetTextAlignment(iText.Layout.Properties.TextAlignment.CENTER)
                    .SetMarginBottom(20);
                document.Add(titulo);

                // Crear tabla
                iText.Layout.Element.Table tabla = new iText.Layout.Element.Table(8).UseAllAvailableWidth();

                // Encabezados
                string[] encabezados = new[] {
            "ID", "Matrícula", "Modelo", "Marca", "Color", "Año Fab.", "Precio", "Categoría"
        };

                PdfFont fontBold = PdfFontFactory.CreateFont(StandardFonts.HELVETICA_BOLD);

                foreach (var header in encabezados)
                {
                    tabla.AddHeaderCell(new Cell()
                        .Add(new Paragraph(header).SetFont(fontBold))
                        .SetBackgroundColor(iText.Kernel.Colors.ColorConstants.LIGHT_GRAY)
                        .SetTextAlignment(iText.Layout.Properties.TextAlignment.CENTER));
                }

                // Filas de datos
                foreach (var v in vehiculos)
                {
                    tabla.AddCell(new Paragraph(v.IdVehiculo.ToString()));
                    tabla.AddCell(new Paragraph(v.Matricula));
                    tabla.AddCell(new Paragraph(v.Modelo));
                    tabla.AddCell(new Paragraph(v.Marca));
                    tabla.AddCell(new Paragraph(v.Color));
                    tabla.AddCell(new Paragraph(v.AnioFab.Year.ToString()));
                    tabla.AddCell(new Paragraph(v.Precio.ToString("C")));
                    tabla.AddCell(new Paragraph(v.Categoria));
                }

                document.Add(tabla);

                document.Close();
                return memoryStream.ToArray();
            }
        }

        // 4. Reporte escudería: nombre + total alquileres

TallleresPaco/Controllers/VehiculosController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TallleresPaco.Models;

namespace TallleresPaco.Controllers
{
    public class VehiculosController : Controller
    {
        private readonly Contexto _context;

        public VehiculosController(Contexto context)
        {
            _context = context;
        }

        // GET: Vehiculos
        public async Task<IActionResult> Index()
        {
            var userIsAdmin = User.IsInRole("Admin");

            var vehiculos = await _context.Vehiculos
                .Where(v => userIsAdmin || v.Estado == "disponible")
                .ToListAsync();

            return View(vehiculos);
        }

        // GET: Vehiculos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculos = await _context.Vehiculos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehiculos == null)
            {
                return NotFound();
            }

            return View(vehiculos);
        }

        // GET: Vehiculos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehiculos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Matricula,Modelo,Marca,Color,AnioFab,Tipo,Precio,Categoria,Estado")] Vehiculos vehiculos)
        {
            //if (ModelState.IsValid)
            {
                _context.Add(vehiculos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehiculos);
        }

        // GET: Vehiculos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculos = await _context.Vehiculos.FindAsync(id);
            if (vehiculos == null)
            {
                return NotFound();
            }
            return View(vehiculos);
        }

        // POST: Vehiculos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Matricula,Modelo,Marca,Color,AnioFab,Tipo,Precio,Categoria")] Vehiculos vehiculos)
        {
            if (id != vehiculos.Id)
            {
                return NotFound();
            }

           
                try
                {
                    var vehiculoExistente = await _context.Vehiculos.FindAsync(id);
                    if (vehiculoExistente == null)
                        return NotFound();

                    // Actualizar solo los campos permitidos (excluyendo Estado)
                    vehiculoExistente.Matricula = vehiculos.Matricula;
                    vehiculoExistente.Modelo = vehiculos.Modelo;
                    vehiculoExistente.Marca = vehiculos.Marca;
                    vehiculoExistente.Color = vehiculos.Color;
                    vehiculoExistente.AnioFab = vehiculos.AnioFab;
                    vehiculoExistente.Tipo = vehiculos.Tipo;
                vehiculoExistente.Precio = new decimal((double)vehiculos.Precio); // vehiculos.Precio;
                    vehiculoExistente.Categoria = vehiculos.Categoria;
                    // Estado no se toca

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiculosExists(vehiculos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            

            return View(vehiculos);
        }

        // GET: Vehiculos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculos = await _context.Vehiculos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehiculos == null)
            {
                return NotFound();
            }

            return View(vehiculos);
        }

        // POST: Vehiculos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehiculo = await _context.Vehiculos.FindAsync(id);
            if (vehiculo != null)
            {
                vehiculo.Estado = "Cancelado";
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool VehiculosExists(int id)
        {
            return _context.Vehiculos.Any(e => e.Id == id);
        }
    }
}

TallleresPaco/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject TallleresPaco.Models.Contexto _context

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TallleresPaco</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TallleresPaco.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TallleresPaco</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @{
                            var usuario = _context.Set<TallleresPaco.Models.Usuarios>()
                            .FirstOrDefault(u => u.Email == User.Identity.Name); 

                            int? usuarioId = usuario?.Id;
                        }

                   

                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SearchFilters" asp-action="Index">Buscar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="Edit" asp-route-id="@usuarioId">Editar Perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Manage">Panel de Reportes</a>
                            </li>
                          
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculos" asp-action="Index">Vehículos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Alquileres" asp-action="Index">Alquileres</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Manage">Panel de Reportes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SearchFilters" asp-action="Index">Buscar</a>
                            </li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TallleresPaco - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>